version: "2.1"
services:
  administration:
    container_name: administration
    build: ./administration
    links:
      - db
    # start only after database is ready for a connection
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "5001:5001"
    # equivalent to docker run -ti; make attaching to terminal
    # and interactivity available
    stdin_open: true
    tty: true

  service:
    container_name: service
    build: ./service
    links:
      - db
    # start only after database is ready for a connection
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "5000:5000"
    # equivalent to docker run -ti; make attaching to terminal
    # and interactivity available
    stdin_open: true
    tty: true

  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    # check if database is ready and fully loaded
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-proot"]
        timeout: 10s
        retries: 10
